/**
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



import { BigDecimal } from 'bigDecimal';




export interface ClientCase { 

    
    caseID: string;

    
    companyID: string;

    
    caseNumber: BigDecimal;

    
    patientFirstName: string;

    
    patientLastName: string;

    
    diagnosis: string;

    
    firstDayOfTravel: Date;

    
    numberTravelDays: BigDecimal;

    
    originCity: string;

    
    destinationCity: string;

    
    quotedPrice: BigDecimal;

}


