/**
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';

import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';



import { Observable }                                        from 'rxjs/Observable';



import { CaseProgressNote } from '../model/caseProgressNote';


import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';





@Injectable()


export class CaseProgressNotesControllerService {


    protected basePath = 'http://127.0.0.1:3000';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }




    /**
     * 
     * 
     * @param where 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    
    public caseProgressNotesCountGet(where?: any, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public caseProgressNotesCountGet(where?: any, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public caseProgressNotesCountGet(where?: any, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public caseProgressNotesCountGet(where?: any, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
    
    





        
        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        
        

        
        
        if (where !== undefined && where !== null) {
        
        
            queryParameters = queryParameters.set('where', <any>where);
        
        }
        



        let headers = this.defaultHeaders;



        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            
            'application/json'
            
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {


            headers = headers.set('Accept', httpHeaderAcceptSelected);

        }

        // to determine the Content-Type header
        const consumes: string[] = [
            
        ];




        return this.httpClient.get(`${this.basePath}/case-progress-notes/count`,
            {

                params: queryParameters,


                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );


    }


    /**
     * 
     * 
     * @param filter 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    
    public caseProgressNotesGet(filter?: any, observe?: 'body', reportProgress?: boolean): Observable<Array<CaseProgressNote>>;
    public caseProgressNotesGet(filter?: any, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CaseProgressNote>>>;
    public caseProgressNotesGet(filter?: any, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CaseProgressNote>>>;
    public caseProgressNotesGet(filter?: any, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
    
    





        
        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        
        

        
        
        if (filter !== undefined && filter !== null) {
        
        
            queryParameters = queryParameters.set('filter', <any>filter);
        
        }
        



        let headers = this.defaultHeaders;



        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            
            'application/json'
            
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {


            headers = headers.set('Accept', httpHeaderAcceptSelected);

        }

        // to determine the Content-Type header
        const consumes: string[] = [
            
        ];




        return this.httpClient.get(`${this.basePath}/case-progress-notes`,
            {

                params: queryParameters,


                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );


    }


    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    
    public caseProgressNotesIdDelete(id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public caseProgressNotesIdDelete(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public caseProgressNotesIdDelete(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public caseProgressNotesIdDelete(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
    
    


        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling caseProgressNotesIdDelete.');
        }




        let headers = this.defaultHeaders;



        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {


            headers = headers.set('Accept', httpHeaderAcceptSelected);

        }

        // to determine the Content-Type header
        const consumes: string[] = [
            
        ];




        return this.httpClient.delete(`${this.basePath}/case-progress-notes/${encodeURIComponent(String(id))}`,
            {


                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );


    }


    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    
    public caseProgressNotesIdGet(id: string, observe?: 'body', reportProgress?: boolean): Observable<CaseProgressNote>;
    public caseProgressNotesIdGet(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CaseProgressNote>>;
    public caseProgressNotesIdGet(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CaseProgressNote>>;
    public caseProgressNotesIdGet(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
    
    


        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling caseProgressNotesIdGet.');
        }




        let headers = this.defaultHeaders;



        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            
            'application/json'
            
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {


            headers = headers.set('Accept', httpHeaderAcceptSelected);

        }

        // to determine the Content-Type header
        const consumes: string[] = [
            
        ];




        return this.httpClient.get(`${this.basePath}/case-progress-notes/${encodeURIComponent(String(id))}`,
            {


                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );


    }


    /**
     * 
     * 
     * @param id 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    
    public caseProgressNotesIdPatch(id: string, body?: CaseProgressNote, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public caseProgressNotesIdPatch(id: string, body?: CaseProgressNote, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public caseProgressNotesIdPatch(id: string, body?: CaseProgressNote, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public caseProgressNotesIdPatch(id: string, body?: CaseProgressNote, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
    
    


        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling caseProgressNotesIdPatch.');
        }






        let headers = this.defaultHeaders;



        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {


            headers = headers.set('Accept', httpHeaderAcceptSelected);

        }

        // to determine the Content-Type header
        const consumes: string[] = [
            
            'application/json'
            
        ];

        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {


            headers = headers.set('Content-Type', httpContentTypeSelected);

        }




        return this.httpClient.patch(`${this.basePath}/case-progress-notes/${encodeURIComponent(String(id))}`,
            {


                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );


    }


    /**
     * 
     * 
     * @param body 
     * @param where 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    
    public caseProgressNotesPatch(body?: CaseProgressNote, where?: any, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public caseProgressNotesPatch(body?: CaseProgressNote, where?: any, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public caseProgressNotesPatch(body?: CaseProgressNote, where?: any, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public caseProgressNotesPatch(body?: CaseProgressNote, where?: any, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
    
    







        
        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        
        

        
        
        if (where !== undefined && where !== null) {
        
        
            queryParameters = queryParameters.set('where', <any>where);
        
        }
        



        let headers = this.defaultHeaders;



        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            
            'application/json'
            
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {


            headers = headers.set('Accept', httpHeaderAcceptSelected);

        }

        // to determine the Content-Type header
        const consumes: string[] = [
            
            'application/json'
            
        ];

        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {


            headers = headers.set('Content-Type', httpContentTypeSelected);

        }




        return this.httpClient.patch(`${this.basePath}/case-progress-notes`,
            {

                params: queryParameters,


                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );


    }


    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    
    public caseProgressNotesPost(body?: CaseProgressNote, observe?: 'body', reportProgress?: boolean): Observable<CaseProgressNote>;
    public caseProgressNotesPost(body?: CaseProgressNote, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CaseProgressNote>>;
    public caseProgressNotesPost(body?: CaseProgressNote, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CaseProgressNote>>;
    public caseProgressNotesPost(body?: CaseProgressNote, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
    
    





        let headers = this.defaultHeaders;



        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            
            'application/json'
            
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {


            headers = headers.set('Accept', httpHeaderAcceptSelected);

        }

        // to determine the Content-Type header
        const consumes: string[] = [
            
            'application/json'
            
        ];

        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {


            headers = headers.set('Content-Type', httpContentTypeSelected);

        }




        return this.httpClient.post(`${this.basePath}/case-progress-notes`,
            {


                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );


    }



